### PR TITLE
Added process id in logs

### PR DESCRIPTION
**Pull request by psquickitjayant**

### CODE REVIEW

**Comment by psquickitjayant** [comment]
@freeformz  this PR should be fine for adding process id.

**Comment by freeformz** [comment]
@psquickitjayant And this should close #32 right?

**Comment by freeformz** [comment]
LGTM +1

**Comment by psquickitjayant** [comment]
@freeformz  yes #32 is solved from this update.

**Comment by freeformz** [comment]
Merged and pushed as 0.3.0

**Pull request merged**
